name: Deploy Storybook to GitHub Pages

on:
  push:
    branches:
      - main # 또는 배포 트리거가 될 브랜치

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # storybook 빌드 파일만 있는 경우, 아래 단계 생략 가능
      # - name: Install dependencies
      #   run: npm ci
      # - name: Build Storybook
      #   run: npm run build-storybook

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: storybook # 빌드 결과 폴더명(예: storybook, storybook-static, dist/storybook/ui-components 등)
